---
driver:
  name: vagrant
  linked_clone: true

  network:
    # - ["forwarded_port", {guest: 80, host: 8080}]

  customize:
    cpus: 2
    memory: 4096
  gui: true
  synced_folders:
    - ["./", "/sources"]
    - ["~/chef-kits", "/chef-kits"]

provisioner:
  name: chef_zero
  # always_update_cookbooks: true
  # deprecations_as_errors: true
  # enforce_idempotency: true
  # multiple_converge: 2
  log_level: info
  require_chef_omnibus: true
  # require_chef_omnibus: 12.19.36
  require_chef_omnibus: 11.18.12
  # require_chef_omnibus: 13


verifier:
  name: inspec

# transport:
#   name: winrm
#   password: vagrant
#   username: vagrant

platforms:
  # - name: ubuntu-16.04
  # -name: centos-6.7
  # - name: centos-7.3
  - name: win2016
  # - name: win2008r2
  # - name: tricky/solaris11-chef
  # - name: tricky/solaris10-chef

suites:
  - name: default
    run_list:
      - recipe[chef_client_version_manager::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      chef_client:
        config:
          log_level: debug
      ohai:
        disabled_plugins: [ ]
